### ISSUE TITLE
Require acceptance of Terms of Service

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/adopt-a-drain#10]
As a User I am not required to accept any terms of service. City of Norfolk would like Users to be required to view and accept the terms.

City of Virginia Beach has implemented this in their repo:
https://github.com/CityOfVirginiaBeach/adopt-a-drain/commit/52c3dd7789381b0fb9d74077fa829ff285c3d353

**Comment by ryayak1460** [comment]
#14 will resolve this.
