### ISSUE TITLE
Add Fairmont Park drains.

### ISSUE THREAD

**Issue by kaxcode** [Code4HR/adopt-a-drain#16]
CSV file is found in code4hr slack group in the #adopta channel.

**Comment by kaxcode** [comment]
CLI into Heorku to add csv info into production db. @kmcurry and @BretFisher have access. Permissions requested.

**Comment by BretFisher** [comment]
Here's how I would load the existing csv stored in the repo, from heroku cli:

for master branch (prod):
`heroku run bundle exec rake data:load_things --app norfolkdrains`

for develop branch:
`heroku run bundle exec rake data:load_things --app norfolkdrains-develop`

**Comment by BretFisher** [comment]
@kaxcode I gave you heroku perms to norfolkdrains-develop. Once we/you get that working I'll give prod access :)

**Comment by kmcurry** [comment]
And the data file is in the repo here: https://github.com/Code4HR/adopt-a-drain/blob/master/norfolk.csv

I'd concatenate to existing.
