### ISSUE TITLE
Set "Give this drain a name" text as background placeholder

### ISSUE THREAD

**Issue by stanzheng** [Code4HR/adopt-a-drain#48]
As a user, when I adopt-a-drain I expect the text "Storm Water Inlet Drain" to be background form text rather than foreground text that I have to erase.

We should make this a background field text

**Comment by kmcurry** [comment]
Have to account for unnamed drain if you remove the default and a person adopts without typing anything

**Comment by ryayak1460** [comment]
I'll take a look.

**Comment by kmcurry** [comment]
A default name is given
