### ISSUE TITLE
Fix Map for -develop

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/adopt-a-drain#50]
norfolkdrains-develop.herokuapp.com does not work because the map does not show.

**Comment by kmcurry** [comment]
Probably Google Maps API key

**Comment by ryayak1460** [comment]
@kmcurry Yep, it has to do with the subdomain not matching the key used.  We could solve this with a second key or including the development domain with the original key.

How do you want to go about this?

**Comment by stanzheng** [comment]
Did I insert the last key?

I can create a second one or just remove the domain restriction..

**Comment by ryayak1460** [comment]
Awesome, thanks, @stanzheng! Now comes the question: where do we use this? I don't actually see the key referenced in code anywhere.  The `app/assets/javascripts/main.js.erb` template doesn't actually use a map key, so is this something explicitly in Heroku?

**Comment by stanzheng** [comment]
@ryayak1460 check where the js for the google maps key is being loaded. 

https://github.com/Code4HR/adopt-a-drain/blob/master/app/views/layouts/application.html.haml#L23

You just have to override the environment variable. Its a railism

Rails.application.secrets.google_maps_javascript_api_key

**Comment by stanzheng** [comment]
yup! probably just needs to be configured in the new environment or in the yaml file. Since these keys are semi-public because they're sent to the client it should be fine to include!

**Comment by ryayak1460** [comment]
Who can update the value in Heroku? You, @stanzheng? @BretFisher? Or will we just update the value in the config file here in the repo?

**Comment by BretFisher** [comment]
ENVVAR's are set for each app in Heroku. Looks like `GOOGLE_MAPS_JAVASCRIPT_API_KEY` is set in both, but it's the same value. I updated the norfolkdrains-develop with the key above and the site seems to work for me. I'll close but reopen if it's not the true fix.
