### ISSUE TITLE
Replace sfwater with adoptstormdrain@norfolk.gov

### ISSUE THREAD

**Issue by kswhite93** [Code4HR/adopt-a-drain#63]
Replace email address with adoptstormdrain@norfolk.gov 
Replace website url with https://norfolkdrains.herokuapp.com/

**Comment by ryayak1460** [comment]
Hi @kswhite93, I took a look at this just now, and I remember updating the contact information for this in [this issue](https://github.com/Code4HR/adopt-a-drain/issues/9) with [this](https://github.com/Code4HR/adopt-a-drain/pull/12/files) pull request.

It sounds like I missed something, but I don't see where.  Could you provide a screenshot or more information so I can help complete this?

**Comment by kswhite93** [comment]
Hi @ryayak1460 ! Everything is working well as far as I know. I opened the issue during one of the hack nights when @kmcurry helped me update a few last links and forgot to close it. I'll close it now, thank you!!!

**Comment by ryayak1460** [comment]
No problem, thank you, @kswhite93! I'll take a look at the other issues in the meantime.  Would you please close any others if they are also non-issues?
