### ISSUE TITLE
Replace San Francisco with Norfolk

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/adopt-a-drain#8]
Brand this version for City of Norfolk Office of Resilience

MVP: Find and replace all

Ideal: Make it configurable using locales

**Comment by ryayak1460** [comment]
#13 will resolve this.

Question: for https://github.com/Code4HR/adopt-a-drain/blob/production/config/locales/en.yml#L105, what should we change the hashtag and Twitter account at the end to?

**Comment by ryayak1460** [comment]
Ready to close.
