### ISSUE TITLE
Update contact email address

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/adopt-a-drain#9]
Kyle Spencer [5:27 PM] 
Please use adoptstormdrain@norfolk.gov  and the video phone number is the best one to use.

**Comment by ryayak1460** [comment]
Updated email in #12, waiting to find out proper copy for phone number before including that update as well.

**Comment by ryayak1460** [comment]
Re: the application sending emails, will we use this email as well when Adopt-a-Drain sends emails?

**Comment by ryayak1460** [comment]
Sweet, looks like we can close this if we don't have to put the video phone number in any specific place.
